name: Deploy Backend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy by pulling code and updating dependencies
        run: |
          # Go to the actual folder on the Windows Server where the Docker compose is running
          cd "C:\Project\PPHSE KTI Backend"

          # 1. Pull the latest code directly on the host machine
          git fetch origin main
          git reset --hard origin/main
          
          # 2. Ensure the container is rebuilt/restarted with the latest changes
          docker compose up -d --build
          docker compose restart sap-mock



          # Note: Because the container runs `npm run dev` (nodemon) via start.sh
          # and the current folder is mounted as a volume (- .:/app), 
          # nodemon will automatically restart the Node.js server upon detecting these file changes!
